name: Main CI

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ci-sample:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
      - name: Extract artifacts
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ env.IMAGE_NAME }}
          path: app/artifacts/.

      - name: Push artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ${{ steps.extract.outputs.destination }}
